### ISSUE TITLE
Invalid image size height 0

### ISSUE THREAD

**Issue by lencioni** [trotzig/likadan#23]
I noticed this error in the output of a Jenkins run (/job/brigade-likadan/524/console). Not sure if it causing actual problems, but I thought that likadan could probably at least give us a more instructive error message.

```
/var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chunky_png-1.3.4/lib/chunky_png/canvas/png_decoding.rb:76:in `from_datastream': Invalid image size, width: 320, height: 0 (ChunkyPNG::ExpectationFailed)
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chunky_png-1.3.4/lib/chunky_png/image.rb:74:in `from_datastream'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chunky_png-1.3.4/lib/chunky_png/canvas/png_decoding.rb:53:in `from_file'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/lib/likadan_runner.rb:70:in `block in <top (required)>'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/lib/likadan_runner.rb:31:in `each'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/lib/likadan_runner.rb:31:in `<top (required)>'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/bin/likadan:13:in `require'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/bin/likadan:13:in `block in <top (required)>'
```

**Comment by lencioni** [comment]
I think this happens when the baseline image doesn't have any height, so it won't happen on the first run, just on subsequent runs. I think this can just be prevented by setting a min-height of 1px on the container.

**Comment by lencioni** [comment]
I'll submit a PR in a couple of minutes.
