### ISSUE TITLE
`crop!': undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by lencioni** [trotzig/likadan#24]
I was running likadan locally and working on a new example that had errors at the time so it wasn't rendering anything (at least I think so, it was a while ago and my memory is foggy now). I noticed this output. It seems that likadan could offer a more instructive error message in this scenario.

```
== Sinatra has ended his set (crowd applauds)
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chunky_png-1.3.4/lib/chunky_png/canvas/operations.rb:171:in `crop!': undefined method `+' for nil:NilClass (NoMethodError)
        from /Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.12/lib/likadan_runner.rb:51:in `block in <top (required)>'
        from /Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.12/lib/likadan_runner.rb:25:in `each'
        from /Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.12/lib/likadan_runner.rb:25:in `<top (required)>'
        from /Users/joe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/joe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.12/bin/likadan:13:in `block in <top (required)>'
```

**Comment by trotzig** [comment]
Was this fixed by https://github.com/trotzig/likadan/commit/77cd777ee3159c7887d39ad09f38c87ad6266356 ?

**Comment by lencioni** [comment]
Yeah, I believe that will avoid this problem.
