### ISSUE TITLE
You have attempted to create more buckets than allowed 

### ISSUE THREAD

**Issue by lencioni** [trotzig/likadan#29]
I just noticed this error in our CI likadan runs:

```
/var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.22/lib/s3/connection.rb:216:in `handle_response': You have attempted to create more buckets than allowed (S3::Error::TooManyBuckets)
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.22/lib/s3/connection.rb:203:in `send_request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.22/lib/s3/connection.rb:88:in `request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.22/lib/s3/service.rb:74:in `service_request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.22/lib/s3/bucket.rb:209:in `bucket_request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.22/lib/s3/bucket.rb:190:in `create_bucket_configuration'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.22/lib/s3/bucket.rb:89:in `save'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/lib/likadan_uploader.rb:18:in `upload_diffs'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/bin/likadan:34:in `<top (required)>'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/bin/likadan:23:in `load'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/bin/likadan:23:in `<main>'
```

I think we can resolve this by upgrading our plan, but it might be nice for likadan to provide a more informative error message in this scenario.

**Comment by lencioni** [comment]
I pushed #30 to address this.

**Comment by trotzig** [comment]
#30 should resolve this issue. Thanks @lencioni!
